### ISSUE TITLE
Would you mind to upload the http folder?

### ISSUE THREAD

**Issue by Blank-Xu** [isemenkov/libpascurl#1]
I can't find the http folder when I run your examples.

The file is `source/http/http.pas`.

So would you mind to upload the http folder?

**Comment by isemenkov** [comment]
I am rewriting all and at that moment this file is not exists yet. You can find last working examples with this file in [branch 9bf9e73](https://github.com/isemenkov/libpascurl/tree/9bf9e7321997a8b9cedd2824209b0d63cafaa5b6).

**Comment by Blank-Xu** [comment]
Ok. Thank you.
